apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-frontend
        image: dlxneamtu/flask-demo:latest
        ports:
        - containerPort: 8888

